nome = input('qual seu nome?')
print('prazer em te conhecer {}'.format(nome))
print('prazer em te conhecer {:20}!'.format(nome))
print('prazer em te conhecer {:>20}!'.format(nome))
print('prazer em te conhecer {:<20}!'.format(nome))
print('prazer em te conhecer {:^20}!'.format(nome))
print('prazer em te conhecer {:=^20}!'.format(nome))
